#!/bin/bash

# Create a new file called myfile.txt and add the string "Hello world"
echo "Hello world" > myfile.txt

# Get the size of myfile.txt in bytes
filesize=$(stat -c%s "myfile.txt")

# Print the size of the file
echo "Size of myfile.txt: $filesize bytes"
